services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: logs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d logs"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata:
